cursos/urls.py
from django.urls import path

from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.home, name="home"),
    path('cursos/<id>/', views.curso, name="curso"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursos.urls')),
]

cursos/models.py
from django.db import models

# Create your models here.

cursos/views.py
from django.shortcuts import render
from utils.curso.factory import make_cursos
from utils.cursos.factory import make_curso


# Create your views here.
def home(request):
    return render(request, 'cursos/pages/home.html', context={
        'cursos': make_cursos(),
    })


def curso(request, id):
    cursos = make_cursos()
    list_keys = [id]
    curso = list(filter(lambda d: d['id'] in list_keys, cursos))

    return render(request, 'cursos/pages/curso-view.html', context={
        'curso': curso[0],
        'is_detail_page': True,
    })


def cursos(request, id):
    return render(request, 'cursos/pages/curso-view.html', context={
        'curso': make_curso(),
        'is_detail_page': True,
    })

cursos/templates/cursos/pages/curso-view.html
{% extends 'global/base.html' %}

{% block title %}ALTERAR | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'cursos/partials/curso.html' %}
</div>
{% endblock content %}

cursos/templates/cursos/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for curso in cursos %}
            {% include 'cursos/partials/curso.html' %}
        {% endfor %}
    </div>
{% endblock content %}

cursos/templates/cursos/partials/curso.html
<div class="curso curso-list-item">
    <div class="curso-cover">
        <a href="{% url 'cursos:curso' curso.id %}">
            {% if is_detail_page is not True %}
                <img src="{{ curso.cover.tumb }}">
            {% endif %}
            {% if is_detail_page is True %}
                <img src="{{ curso.cover.url }}">
            {% endif %}
        </a>
    </div>
    <div class="curso-title-container">
        <h2 class="curso-title">
            <a href="{% url 'cursos:curso' curso.id %}">
                {{ curso.title }}
            </a>
        </h2>
    </div>

    <div class="curso-category">
        <span class="curso-category-item">
            <i class="fas fa-graduation-cap"></i>
            <span>{{ curso.category.name }}</span>
        </span>
        <span class="curso-category-item">
            <i class="fas fa-laptop"></i>
            <span>{{ curso.category.type }}</span>
        </span>
    </div>

    <div class="curso-content">
        <p>{{ curso.short_description }}</p>
    </div>

    <div class="curso-time-container">
        <div class="curso-time curso-preparation">
            <h3 class="curso-time-title"><i class="fas fa-hourglass"></i> Tempo</h3>
            <div class="curso-time-text">
                {{ curso.time_description }} 
            </div>
        </div>
        <div class="curso-time curso-servings">
            <h3 class="curso-time-title"><i class="fas fa-clock"></i> Carga Horária</h3>
            <div class="curso-time-text">
                {{ curso.hours_description }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="curso-footer">
            <a class="curso-read-more button button-dark button-full-width" href="{% url 'cursos:curso' curso.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {{ curso.long_description|safe }}
        </div>
    {% endif %}

</div>

cursos/templates/cursos/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://gilhhb.ninja" target="_blank" rel="noreferrer noopener">By Gil H. H. Belei</a>
    </div>
    <div class="powered">
      <h4><i class="fas fa-phone-alt" aria-hidden="true"></i> CONTATO</h4>
      <a href="tel:08007291721" target="_blank" rel="noopener">
        0800 729 1721
     </a>
    </div>
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

cursos/templates/cursos/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'cursos/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'global/css/global-styles.css' %}">

cursos/templates/cursos/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'cursos:home' %}">
                <i class="fas fa-solid fa-graduation-cap"> </i> 
                <span class="main-logo-text"> Cursos de Graduação </span> 
                <img src="https://ead.faesa.br/hs-fs/hubfs/EAD_FAESA_branco.png?width=200&height=53&name=EAD_FAESA_branco.png">
            </a>
        </h1>
    </div>
</header>

cursos/templates/cursos/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>